version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=Sai@123456
      - MYSQL_DB=flaskapplication
    restart: on-failure

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: flaskapplication
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: Sai@123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # ‚Üê MUST BE THIS
#    ports:
#     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

# === Flask App ===
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prep_mining_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=Sai@123456
      - MYSQL_DB=flaskapplication
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 app:app

volumes:
  mysql-data:
